### ISSUE TITLE
Thank you and a question

### ISSUE THREAD

**Issue by editempura** [LaughingLeader-DOS2-Mods/DivinityModManager#1]
Hi,

thank you for doing this. Mod manager provided by Larian is quite terrible so any improvement in this space is vastly appreciated ;)

I've noticed one thing - Divinity doesn't always read the mods subscribed to in Steam Workshops. There are two folders where the *.pak files are stored:
Workshops folder: **Steam/steamapps/workshop/content/435150/** 
Mods folder: **Documents/Larian Studios/Divinity.../Mods**

Your mod manager automatically identified Workshop folder path and you also have a button to go to Divinity Mods folder. However, there is no reconciliation between the two folders. I have tested by removing a mod from Mods folder and it is removed from the load order list even though technically I'm still subscribed to it in Steam.

Do you have any plans to add this functionality to automatically reconcile two folders and keep them in sync?

Thank you so much for your hard work!
All the best.

My question is this - does the mod manager have addded functionality of moving the *.pak files to the Mods folder? If not, how do you resolve the situation in which you set load order list which includes mods that do not exist in Mods folder because of the bug.

**Comment by LaughingLeader** [comment]
Hi there. There's a whole update screen that shows you new mods and mod updates in your workshop folder, which allows you to copy the selected mods to your mods folder:

![ModUpdatesView](https://user-images.githubusercontent.com/2529658/70366627-5a590f80-185e-11ea-9672-683da4afb4d1.png)

You simply have to click the little "Updates" button when there's updates available to see this view. From there, everything gets automatically selected, at which point you can unselect what you don't want to copy, or just hit "Copy selected" to move all the new mods/updates over.

---

For an explanation, what's happening is when you subscribe to a mod on Steam, it downloads the mod to your workshop folder. Then when you launch the game, the mods in your workshop folder get copied to your mods folder, which the game then reads from when determining what you can activate.

The issue for some people is the game fails to copy the workshop mods to your documents folder. Not exactly sure why that happens - Could be the game is unable to handle usernames with non-ascii characters, or it could be read/write permission issues, or some other obscure problem.

Additionally Steam sometimes fails to download newly subscribed workshop items or updates (it simply doesn't download them in this case), which is usually fixed by restarting Steam.

---

Anyway, morale of the story is the game doesn't actually load mods from your workshop folder - It just copies them to your documents folder when it detects new versions / new mods.

The mod manager can ease that a bit by allowing you to see new updates/mods and copy them over with a few clicks.

**Comment by editempura** [comment]
Excellent! I’ve actually didn’t notice the Updates page because I couldn’t access it. I’ve tested what you said - everything is working fine. 

Thanks!
